# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: setup git auth
        env:
          email: 'ti@perfilline.com.br'
          username: 'perfilline'
          access_token: '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'
        run: |
          git config --global credential.helper store
          echo "https://${access_token}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global user.email $email
          git config --global user.name $username
      - name: deploy to gh-pages
        run: |
          npm i
          NODE_ENV=production
          npm run build
          cd dist
          git init
          git add -A
          git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
          git push -f "https://github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
